/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package config.vistas;

import controller.ProblemaActivistaController;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author marki
 */
public class FrmProblemasActivistas extends javax.swing.JPanel {
    private ProblemaActivistaController paController;
    private TableRowSorter sorter;
    /**
     * Creates new form FrmProblemasActivistas
     */
    public FrmProblemasActivistas() {
        initComponents();
        paController = new ProblemaActivistaController();
        
        btnEliminar.setVisible(false);
        cargarDatos();
        
        sorter = new TableRowSorter(tblProblemaActivista.getModel());
        tblProblemaActivista.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblProblemaId = new javax.swing.JLabel();
        lblActivistaId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblDescripción = new javax.swing.JLabel();
        txtProblemaID = new javax.swing.JTextField();
        txtActivistaID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripción = new javax.swing.JTextArea();
        btnAsignar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProblemaActivista = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        comboBusqueda = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Administración de relación con Problemas-Activistas");

        lblId.setText("ID:");

        lblProblemaId.setText("ID_Problema:");

        lblActivistaId.setText("ID_Activista:");

        txtID.setEditable(false);
        txtID.setEnabled(false);

        lblDescripción.setText("Descripción:");

        txtProblemaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProblemaIDActionPerformed(evt);
            }
        });

        txtDescripción.setColumns(20);
        txtDescripción.setRows(5);
        jScrollPane1.setViewportView(txtDescripción);

        btnAsignar.setText("ASIGNAR");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblProblemaActivista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProblemaActivista);

        lblBuscar.setText("Buscar por:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        comboBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID de Activista", "ID de Problema" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar)
                            .addComponent(btnAsignar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescripción, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblActivistaId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblProblemaId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProblemaID, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(txtActivistaID))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar)
                    .addComponent(comboBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProblemaId)
                    .addComponent(txtProblemaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblActivistaId)
                            .addComponent(txtActivistaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripción)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAsignar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProblemaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProblemaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProblemaIDActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        filtrarTabla();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        try {
        
            int idProblema = Integer.parseInt(txtProblemaID.getText());
            int idActivista = Integer.parseInt(txtActivistaID.getText());
            

            if (idProblema == -0 || idActivista == -0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Error",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            
            boolean exito;
            if (btnAsignar.getText().equals("ASIGNAR")) {

                // Ahora regresa boolean
                        exito = paController.asignarActivista(idProblema, idActivista);

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Activista asignado a Problema correctamente.");
                    limpiarCampos();
                }
            }
             else {
                    JOptionPane.showMessageDialog(
                            this,
                            "Ocurrió un error al asignar Activista a Problema.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                    limpiarCampos();
                }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
            int idProblema = Integer.parseInt(txtProblemaID.getText());
            int idActivista = Integer.parseInt(txtActivistaID.getText());
            
            int confirm = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar esta asignación?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
                boolean exito = paController.eliminarAsignacion(idProblema, idActivista);
                
                if(exito){
                    JOptionPane.showMessageDialog(this, "Se ha eliminado esta asignación correctamente");
                }else{
                    JOptionPane.showMessageDialog(this, "Hubo un error al borrar la asignación", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                limpiarCampos();
            }else{
                return;
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void filtrarTabla(){
        String texto = txtBuscar.getText();
        String seleccion = comboBusqueda.getSelectedItem().toString();
        
        int columna = 0;
        
        if(seleccion.equals("ID de Activista")){
            columna = 2;
            tblProblemaActivista.setModel(paController.obtenerTablaPorActivista(Integer.parseInt(txtBuscar.getText())));
        }else if(seleccion.equals("ID de Problema")){
            columna = 1;
            tblProblemaActivista.setModel(paController.obtenerTablaPorProblema(Integer.parseInt(txtBuscar.getText())));
        }
        
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, columna));
    }
    
    private void limpiarCampos(){
        txtID.setText("");
        txtBuscar.setText("");
        txtActivistaID.setText("");
        txtProblemaID.setText("");
        txtDescripción.setText("");
    }
    
    private void cargarDatos(){
        int fila = tblProblemaActivista.getSelectedRow();
        if(fila >= 0){
            txtID.setText(tblProblemaActivista.getValueAt(fila, 0).toString());
            txtProblemaID.setText(tblProblemaActivista.getValueAt(fila, 1).toString());
            txtActivistaID.setText(tblProblemaActivista.getValueAt(fila, 2).toString());
            txtDescripción.setText(tblProblemaActivista.getValueAt(fila, 3).toString());
            
            btnAsignar.setText("ASIGNAR");
            btnEliminar.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> comboBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblActivistaId;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDescripción;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblProblemaId;
    private javax.swing.JTable tblProblemaActivista;
    private javax.swing.JTextField txtActivistaID;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescripción;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtProblemaID;
    // End of variables declaration//GEN-END:variables
}
