/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package config.vistas;

import controller.ActivistaController;
import controller.ClienteController;
import controller.ProblemaActivistaController;
import controller.ProblemaController;
import model.Activista;
import model.Cliente;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author martinbl
 */
public class FrmProblemas extends javax.swing.JPanel {

    private Cliente cliente;
    private ClienteController clController;
    private ActivistaController acController;
    private ProblemaController pController;
    private ProblemaActivistaController paController;
    private Activista activista;

    /**
     * Creates new form FrmProblemas
     */
    public FrmProblemas() {
        initComponents();
        
        clController = new ClienteController();
        acController = new ActivistaController();
        pController = new ProblemaController();
        paController = new ProblemaActivistaController();
        cargarProblemas();
    }
    
    private void cargarProblemas(){
        tblProblemas.setModel(pController.obtenerTablaProblemas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblFchIni = new javax.swing.JLabel();
        lblFchFin = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtFchInicio = new com.toedter.calendar.JDateChooser();
        txtFchFin = new com.toedter.calendar.JDateChooser();
        cmbEstado = new javax.swing.JComboBox<>();
        btnClientes = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProblemas = new javax.swing.JTable();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Administración de Problemas");

        lblID.setText("ID");

        lblDesc.setText("DESCRIPCIÓN");

        lblFchIni.setText("FECHA INICIO");

        lblFchFin.setText("FECHA FIN");

        lblEstado.setText("ESTADO");

        lblCliente.setText("CLIENTE");

        txtID.setEditable(false);
        txtID.setEnabled(false);

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Concluido", "Cancelado" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        btnClientes.setText("Buscar ");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCliente.setEditable(false);
        txtCliente.setEnabled(false);

        tblProblemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProblemas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProblemasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblProblemasMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblProblemas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblID)
                            .addGap(74, 74, 74)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDesc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFchIni)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFchInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFchFin)
                                .addComponent(lblEstado)
                                .addComponent(lblCliente))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFchFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnClientes)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesc)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFchIni)
                            .addComponent(txtFchInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFchFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEstado)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFchFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClientes)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar))))
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarProblema();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        DlgBuscarClientes dlg = new DlgBuscarClientes(frame, true); // modal
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true); // esto bloquea hasta cerrar el diálogo

        // Después de cerrar, obtener el cliente seleccionado
        Integer idCliente = dlg.getClienteSeleccionado();
        if (idCliente != null) {
            this.cliente = clController.obtenerCliente(idCliente);
            txtCliente.setText(this.cliente.getNombre());
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void tblProblemasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProblemasMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProblemasMouseReleased

    private void tblProblemasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProblemasMouseClicked
         cargarDatos();
    }//GEN-LAST:event_tblProblemasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFchFin;
    private javax.swing.JLabel lblFchIni;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblProblemas;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextArea txtDesc;
    private com.toedter.calendar.JDateChooser txtFchFin;
    private com.toedter.calendar.JDateChooser txtFchInicio;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables

    private void guardarProblema() {
        try {
        
            String descripcion = txtDesc.getText().trim(); 
            String estado = cmbEstado.getSelectedItem().toString().trim();
            Date fechaInicio = (Date) txtFchInicio.getDate();
            Date fechaFin = (Date) txtFchFin.getDate();

            if (descripcion.isEmpty() || fechaFin == null || fechaInicio == null || this.cliente == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios.",
                        "Error",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            java.sql.Date sqlDateInicio = new java.sql.Date(fechaInicio.getTime());
            java.sql.Date sqlDateFin = new java.sql.Date(fechaFin.getTime());
            
            boolean exito;
            if (btnGuardar.getText().equals("GUARDAR")) {

                // Ahora regresa boolean
                        exito = pController.agregarProblema(
                        sqlDateInicio,
                        sqlDateFin,
                        estado,
                        this.cliente.getIdCliente(),
                        descripcion
                );

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Problema guardado correctamente.");
                }
            }else{
                int id = Integer.parseInt(txtID.getText());
                exito = pController.actualizarProblema(id, sqlDateFin, sqlDateFin, estado, this.cliente.getIdCliente());
                if (exito){
                    JOptionPane.showMessageDialog(this, "Problema actualizado correctamente");
                }
            }
            if (exito){
                cargarProblemas();
                limpiarCampos();
            } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "Ocurrió un error al guardar el problema.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    //  
    private void cargarDatos(){
        int fila = tblProblemas.getSelectedRow();
        if (fila >= 0 ){
            txtID.setText(tblProblemas.getValueAt(fila, 0).toString());
            
            txtFchInicio.setDate((Date) tblProblemas.getValueAt(fila, 1));
            txtFchFin.setDate((Date) tblProblemas.getValueAt(fila, 2));

            cmbEstado.setSelectedItem(tblProblemas.getValueAt(fila, 3).toString());
            
            txtCliente.setText(tblProblemas.getValueAt(fila, 4).toString());
            txtDesc.setText(tblProblemas.getValueAt(fila, 5).toString());
            
            btnGuardar.setText("Actualizar");
            
        }
    }
     
    private void limpiarCampos() {
        txtID.setText("0");
        txtDesc.setText("");
        txtFchInicio.setDate(null);
        txtFchFin.setDate(null);
        cmbEstado.setSelectedIndex(0);
        txtCliente.setText("");
        this.cliente = null; 
        btnGuardar.setText("GUARDAR");
    
    }
    
    
    
    
    
}
